WIP: added documentation of contracts.
solson/rust-nightly-nix pull request #10
Opened 2016-11-21 21:58 UTC by ethanpailes

I'm not sure I understand exactly what is going on with each function I added documentation for, so please let me know if I'm wrong. In particular I'm worried about my explanation of rustcWithSysroots.

2016-11-21 22:07 UTC, Ericson2314 commented
https://github.com/QuiltOS/QuiltOS/blob/master/default.nix should help with the `rustcWithSysroots`. Also see https://github.com/QuiltOS/QuiltOS/commit/89c1bf238beee3b7ffc660fdd1e3676ce8253cd0 for the optional hash argument.

2016-11-21 22:31 UTC, ethanpailes commented
I will add some more specifics about the rustcWithSysroots function. The optional hash does seem like a useful feature to document. I had been reading the `@` symbol as pretty much the same as `@` in Haskell (a pattern-matching alias). Is that what is going on in lines like
```
{ date ? defaultDate, system ? thisSys, ... } @ args:
```

2016-11-22 02:43 UTC, Ericson2314 commented
Yes. The nix ideoms is a bit backwards with the args on the right (it might work both ways).

2016-11-22 15:12 UTC, ethanpailes commented
Cool. Are there any more issues you want me to resolve with this PR?

2016-11-22 15:32 UTC, Ericson2314 requested changes
Just a few nits. Thanks again!

2016-11-22 15:32 UTC, Ericson2314 commented on README.md
> +rust-nightly-nix will just trust whatever it gets.
Actually it will blindly trust the hash mozilla provides (i.e. that blob is unhashed) and then use that the verify the actual download.

2016-11-22 15:32 UTC, Ericson2314 commented on README.md
> +### Documentation
"Invocation", maybe? The whole readme is documentation :).

2016-11-22 15:32 UTC, Ericson2314 commented on README.md
> +useful if you want to make `rust-std` avalable to `rustc`.
If you could make an example from my QuiltOS link, that would be great!

2016-11-22 16:10 UTC, ethanpailes commented on README.md
> +### Documentation
I did feel a little weird about calling it documentation for just that reason. I was trying to convey the fact that this section contains technical documentation of the function contracts.

2016-11-22 16:10 UTC, ethanpailes commented on README.md
> +rust-nightly-nix will just trust whatever it gets.
I'll add the fix.

2016-11-22 16:16 UTC, Ericson2314 commented on README.md
> +### Documentation
Yeah I get where you are coming from. I had to sleep on it before I came up with "Invocation", and that's not necessarily much better.

2016-11-22 16:16 UTC, ethanpailes commented on README.md
> +useful if you want to make `rust-std` avalable to `rustc`.
I will do that. Is the goal of the little snippet in your QuiltOS link to put multiple `rust-std` packages in scope for building rustc against?

2016-11-22 16:17 UTC, Ericson2314 commented on README.md
> +useful if you want to make `rust-std` avalable to `rustc`.
For using rustc to cross-compile for different targets

2016-11-22 16:20 UTC, ethanpailes commented
Also could you help me remember to squash before we merge? I seem to have let a .swp file end up in the git history, so it is probably best to clean up a bit.

2016-11-22 17:47 UTC, Ericson2314 commented on README.md
> +`rustc`.
Err its not the *build* of rustc but the *use* of rustc.

2016-11-22 17:49 UTC, Ericson2314 commented
Fix that one last little thing and then it should be good! If you want to squash all your commits I can have github can do that automatically on merge.

2016-11-22 17:49 UTC, Ericson2314 approved these changes

2016-11-22 18:03 UTC, ethanpailes commented
Everything should be squashed

2016-11-24 22:49 UTC, merged

2016-11-24 22:50 UTC, Ericson2314 commented
Thanks! There is one more "use" vs "build" but I'll just reword myself.

2016-11-25 15:42 UTC, ethanpailes commented
Oh, I'm sorry I missed that. I realized after I squashed that it makes the previous conversation attached to specific lines go away.

2016-11-28 00:41 UTC, Ericson2314 commented
Yeah GitHub is bad about losing line notes